Use a for loop and export GOOS/GOARCH

diff --git a/buildbuddy.yaml b/buildbuddy.yaml
--- a/buildbuddy.yaml
+++ b/buildbuddy.yaml
@@ -69,13 +69,17 @@ actions:
     steps:
       - run: *install_go
       - run: *install_gh_cli
-      - run: 'if [[ -z "$GIT_TAG" ]]; then echo "Error: GIT_TAG must be set"; exit 1; fi'
+      - run: |
+          if [[ -z "$GIT_TAG" ]]; then echo "Error: GIT_TAG must be set"; exit 1; fi
       - run: |
           source ~/.bashrc
+          mkdir -p /tmp/ninja-zips
           for pair in linux/amd64 linux/arm64 darwin/amd64 darwin/arm64; do
-            GOOS=${pair%/*} GOARCH=${pair#*/} go build -ldflags="-s -w" cmd/ninja/ninja.go \
-              && zip $BUILDBUDDY_ARTIFACTS_DIRECTORY/ninja-${pair%/*}-${pair#*/}.zip ninja
+            export GOOS=${pair%/*} GOARCH=${pair#*/}
+            go build -ldflags="-s -w" cmd/ninja/ninja.go \
+              && zip /tmp/ninja-zips/ninja-$GOOS-$GOARCH.zip ninja
           done
-      - run: 'GH_TOKEN=$RENINJA_RELEASE_TOKEN gh release create "$GIT_TAG" --generate-notes --draft --title="Version $GIT_TAG" --verify-tag'
-      - run: 'GH_TOKEN=$RENINJA_RELEASE_TOKEN gh release upload "$GIT_TAG" $BUILDBUDDY_ARTIFACTS_DIRECTORY/ninja-*.zip'
-      - run: 'GH_TOKEN=$RENINJA_RELEASE_TOKEN gh release edit "$GIT_TAG" --draft=false'
+      - run: GH_TOKEN=$RENINJA_RELEASE_TOKEN gh release create "$GIT_TAG" --generate-notes --draft --title="Version $GIT_TAG" --verify-tag
+      - run: GH_TOKEN=$RENINJA_RELEASE_TOKEN gh release upload "$GIT_TAG" /tmp/ninja-zips/ninja-*.zip
+      - run: GH_TOKEN=$RENINJA_RELEASE_TOKEN gh release edit "$GIT_TAG" --draft=false
+      - run: mv /tmp/ninja-zips/ninja-*.zip $BUILDBUDDY_ARTIFACTS_DIRECTORY/
